# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notice_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NoticeDialog(object):
    def setupUi(self, NoticeDialog):
        NoticeDialog.setObjectName("NoticeDialog")
        NoticeDialog.resize(428, 485)
        NoticeDialog.setStyleSheet("QFrame#frame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"QDialog#Dialog{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(NoticeDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(NoticeDialog)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.notice_title_widget = QtWidgets.QWidget(self.frame)
        self.notice_title_widget.setMinimumSize(QtCore.QSize(0, 100))
        self.notice_title_widget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.notice_title_widget.setStyleSheet("background-color: rgb(228, 234, 238);\n"
"border-top-left-radius: 20px;\n"
"    border-top-right-radius: 20px;")
        self.notice_title_widget.setObjectName("notice_title_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.notice_title_widget)
        self.horizontalLayout.setContentsMargins(25, 30, 25, 30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_lab = QtWidgets.QLabel(self.notice_title_widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.title_lab.setFont(font)
        self.title_lab.setObjectName("title_lab")
        self.horizontalLayout.addWidget(self.title_lab)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.close_btn = QtWidgets.QPushButton(self.notice_title_widget)
        self.close_btn.setMinimumSize(QtCore.QSize(45, 45))
        self.close_btn.setMaximumSize(QtCore.QSize(45, 45))
        self.close_btn.setText("")
        self.close_btn.setObjectName("close_btn")
        self.horizontalLayout.addWidget(self.close_btn)
        self.verticalLayout_3.addWidget(self.notice_title_widget)
        self.contents = QtWidgets.QWidget(self.frame)
        self.contents.setMinimumSize(QtCore.QSize(0, 240))
        self.contents.setObjectName("contents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contents)
        self.verticalLayout_2.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_edit = QtWidgets.QLineEdit(self.contents)
        self.title_edit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.title_edit.setFont(font)
        self.title_edit.setStyleSheet("border-radius:5px;\n"
"border: 0.5px solid gray;")
        self.title_edit.setFrame(True)
        self.title_edit.setObjectName("title_edit")
        self.verticalLayout_2.addWidget(self.title_edit)
        self.contents_edit = QtWidgets.QTextEdit(self.contents)
        self.contents_edit.setMinimumSize(QtCore.QSize(0, 220))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.contents_edit.setFont(font)
        self.contents_edit.setStyleSheet("border-radius:5px;\n"
"border: 0.5px solid gray;")
        self.contents_edit.setFrameShape(QtWidgets.QFrame.Box)
        self.contents_edit.setObjectName("contents_edit")
        self.verticalLayout_2.addWidget(self.contents_edit)
        self.verticalLayout_3.addWidget(self.contents)
        self.bottom_widet = QtWidgets.QWidget(self.frame)
        self.bottom_widet.setMaximumSize(QtCore.QSize(16777215, 50))
        self.bottom_widet.setObjectName("bottom_widet")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottom_widet)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(138, 47, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.ok_btn = QtWidgets.QPushButton(self.bottom_widet)
        self.ok_btn.setMinimumSize(QtCore.QSize(200, 50))
        self.ok_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ok_btn.setStyleSheet("background-color: rgb(20, 200, 113);\n"
"border-radius:5px;\n"
"color:white;")
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout_2.addWidget(self.ok_btn)
        spacerItem2 = QtWidgets.QSpacerItem(138, 47, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.bottom_widet)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(NoticeDialog)
        QtCore.QMetaObject.connectSlotsByName(NoticeDialog)

    def retranslateUi(self, NoticeDialog):
        _translate = QtCore.QCoreApplication.translate
        NoticeDialog.setWindowTitle(_translate("NoticeDialog", "Dialog"))
        self.title_lab.setText(_translate("NoticeDialog", "공지작성창"))
        self.title_edit.setPlaceholderText(_translate("NoticeDialog", "공지 제목을 작성하세요"))
        self.contents_edit.setPlaceholderText(_translate("NoticeDialog", "공지 내용을 작성하세요"))
        self.ok_btn.setText(_translate("NoticeDialog", "추가하기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NoticeDialog = QtWidgets.QDialog()
    ui = Ui_NoticeDialog()
    ui.setupUi(NoticeDialog)
    NoticeDialog.show()
    sys.exit(app.exec_())
