# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todo_list_widget_for_admin_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TodoList(object):
    def setupUi(self, TodoList):
        TodoList.setObjectName("TodoList")
        TodoList.resize(445, 102)
        self.horizontalLayout = QtWidgets.QHBoxLayout(TodoList)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_frame = QtWidgets.QFrame(TodoList)
        self.main_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.main_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.h_lay = QtWidgets.QHBoxLayout()
        self.h_lay.setSpacing(0)
        self.h_lay.setObjectName("h_lay")
        self.todo_title = QtWidgets.QCheckBox(self.main_frame)
        self.todo_title.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.todo_title.setFont(font)
        self.todo_title.setIconSize(QtCore.QSize(16, 16))
        self.todo_title.setObjectName("todo_title")
        self.h_lay.addWidget(self.todo_title)
        self.end_time = QtWidgets.QLabel(self.main_frame)
        self.end_time.setObjectName("end_time")
        self.h_lay.addWidget(self.end_time)
        self.del_btn = QtWidgets.QPushButton(self.main_frame)
        self.del_btn.setMaximumSize(QtCore.QSize(24, 24))
        self.del_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.del_btn.setIcon(icon)
        self.del_btn.setIconSize(QtCore.QSize(15, 15))
        self.del_btn.setObjectName("del_btn")
        self.h_lay.addWidget(self.del_btn)
        self.verticalLayout.addLayout(self.h_lay)
        self.line = QtWidgets.QFrame(self.main_frame)
        self.line.setStyleSheet("background-color: #E4EAEE;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.todo_detail = QtWidgets.QLabel(self.main_frame)
        self.todo_detail.setMinimumSize(QtCore.QSize(0, 0))
        self.todo_detail.setObjectName("todo_detail")
        self.verticalLayout.addWidget(self.todo_detail)
        self.horizontalLayout.addWidget(self.main_frame)

        self.retranslateUi(TodoList)
        QtCore.QMetaObject.connectSlotsByName(TodoList)

    def retranslateUi(self, TodoList):
        _translate = QtCore.QCoreApplication.translate
        TodoList.setWindowTitle(_translate("TodoList", "Form"))
        self.todo_title.setText(_translate("TodoList", "투두리스트 제목"))
        self.end_time.setText(_translate("TodoList", "완료시간"))
        self.todo_detail.setText(_translate("TodoList", "할일 세부사항"))
from main_code.front.ui import my_qrc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TodoList = QtWidgets.QWidget()
    ui = Ui_TodoList()
    ui.setupUi(TodoList)
    TodoList.show()
    sys.exit(app.exec_())
