# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'message_label_right.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RightMessage(object):
    def setupUi(self, RightMessage):
        RightMessage.setObjectName("RightMessage")
        RightMessage.resize(815, 63)
        RightMessage.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.horizontalLayout = QtWidgets.QHBoxLayout(RightMessage)
        self.horizontalLayout.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.widget = QtWidgets.QWidget(RightMessage)
        self.widget.setMinimumSize(QtCore.QSize(0, 45))
        self.widget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.widget.setStyleSheet("background-color: #14C871;\n"
"    border-top-left-radius: 20px;\n"
"    border-bottom-left-radius: 20px;\n"
"    border-bottom-right-radius:20px;\n"
"color:white;")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(RightMessage)
        QtCore.QMetaObject.connectSlotsByName(RightMessage)

    def retranslateUi(self, RightMessage):
        _translate = QtCore.QCoreApplication.translate
        RightMessage.setWindowTitle(_translate("RightMessage", "Form"))
        self.label.setText(_translate("RightMessage", "이건 나의 메세지 메세지"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RightMessage = QtWidgets.QWidget()
    ui = Ui_RightMessage()
    ui.setupUi(RightMessage)
    RightMessage.show()
    sys.exit(app.exec_())
