# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_todo_edit_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminTodoDialog(object):
    def setupUi(self, AdminTodoDialog):
        AdminTodoDialog.setObjectName("AdminTodoDialog")
        AdminTodoDialog.resize(430, 510)
        AdminTodoDialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.verticalLayout = QtWidgets.QVBoxLayout(AdminTodoDialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.profile_widget = QtWidgets.QWidget(AdminTodoDialog)
        self.profile_widget.setMinimumSize(QtCore.QSize(0, 100))
        self.profile_widget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.profile_widget.setStyleSheet("background-color: rgb(228, 234, 238);")
        self.profile_widget.setObjectName("profile_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.profile_widget)
        self.horizontalLayout.setContentsMargins(25, 30, 25, 30)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.photo_lab = QtWidgets.QLabel(self.profile_widget)
        self.photo_lab.setMinimumSize(QtCore.QSize(45, 45))
        self.photo_lab.setMaximumSize(QtCore.QSize(45, 45))
        self.photo_lab.setObjectName("photo_lab")
        self.horizontalLayout.addWidget(self.photo_lab)
        self.name_lab = QtWidgets.QLabel(self.profile_widget)
        self.name_lab.setMinimumSize(QtCore.QSize(100, 45))
        self.name_lab.setObjectName("name_lab")
        self.horizontalLayout.addWidget(self.name_lab)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancel_lab = QtWidgets.QPushButton(self.profile_widget)
        self.cancel_lab.setMinimumSize(QtCore.QSize(24, 45))
        self.cancel_lab.setMaximumSize(QtCore.QSize(24, 16777215))
        self.cancel_lab.setObjectName("cancel_lab")
        self.horizontalLayout.addWidget(self.cancel_lab)
        self.verticalLayout.addWidget(self.profile_widget)
        self.scrollArea = QtWidgets.QScrollArea(AdminTodoDialog)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 430, 326))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.admin_todo_lay = QtWidgets.QVBoxLayout()
        self.admin_todo_lay.setObjectName("admin_todo_lay")
        self.verticalLayout_3.addLayout(self.admin_todo_lay)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setMinimumSize(QtCore.QSize(35, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.h_bottom_lay = QtWidgets.QHBoxLayout()
        self.h_bottom_lay.setObjectName("h_bottom_lay")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h_bottom_lay.addItem(spacerItem2)
        self.admit_btn = QtWidgets.QPushButton(AdminTodoDialog)
        self.admit_btn.setMinimumSize(QtCore.QSize(132, 50))
        self.admit_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.admit_btn.setStyleSheet("background-color: rgb(20, 200, 113);\n"
"border-radius:5px;\n"
"color:white;")
        self.admit_btn.setObjectName("admit_btn")
        self.h_bottom_lay.addWidget(self.admit_btn)
        self.cancel_btn = QtWidgets.QPushButton(AdminTodoDialog)
        self.cancel_btn.setMinimumSize(QtCore.QSize(132, 50))
        self.cancel_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.cancel_btn.setStyleSheet("\n"
"border-radius:5px;\n"
"border: 0.5px solid gray;")
        self.cancel_btn.setObjectName("cancel_btn")
        self.h_bottom_lay.addWidget(self.cancel_btn)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.h_bottom_lay.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.h_bottom_lay)

        self.retranslateUi(AdminTodoDialog)
        QtCore.QMetaObject.connectSlotsByName(AdminTodoDialog)

    def retranslateUi(self, AdminTodoDialog):
        _translate = QtCore.QCoreApplication.translate
        AdminTodoDialog.setWindowTitle(_translate("AdminTodoDialog", "Dialog"))
        self.photo_lab.setText(_translate("AdminTodoDialog", "사진"))
        self.name_lab.setText(_translate("AdminTodoDialog", "이름"))
        self.cancel_lab.setText(_translate("AdminTodoDialog", "PushButton"))
        self.pushButton.setText(_translate("AdminTodoDialog", "추가"))
        self.admit_btn.setText(_translate("AdminTodoDialog", "확인"))
        self.cancel_btn.setText(_translate("AdminTodoDialog", "취소"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminTodoDialog = QtWidgets.QDialog()
    ui = Ui_AdminTodoDialog()
    ui.setupUi(AdminTodoDialog)
    AdminTodoDialog.show()
    sys.exit(app.exec_())
