# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_todo_check.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MemberWidget(object):
    def setupUi(self, MemberWidget):
        MemberWidget.setObjectName("MemberWidget")
        MemberWidget.resize(737, 60)
        MemberWidget.setStyleSheet("")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(MemberWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(MemberWidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(35, -1, 35, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(574, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(20, 30))
        self.pushButton.setIconSize(QtCore.QSize(27, 16))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.horizontalLayout_2.addWidget(self.frame)

        self.retranslateUi(MemberWidget)
        QtCore.QMetaObject.connectSlotsByName(MemberWidget)

    def retranslateUi(self, MemberWidget):
        _translate = QtCore.QCoreApplication.translate
        MemberWidget.setWindowTitle(_translate("MemberWidget", "Form"))
        self.label_2.setText(_translate("MemberWidget", "이름"))
        self.label.setText(_translate("MemberWidget", "직급"))
        self.pushButton.setText(_translate("MemberWidget", "보기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MemberWidget = QtWidgets.QWidget()
    ui = Ui_MemberWidget()
    ui.setupUi(MemberWidget)
    MemberWidget.show()
    sys.exit(app.exec_())
