# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todo_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TodoForm(object):
    def setupUi(self, TodoForm):
        TodoForm.setObjectName("TodoForm")
        TodoForm.resize(785, 163)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(TodoForm)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_frame = QtWidgets.QFrame(TodoForm)
        self.main_frame.setMinimumSize(QtCore.QSize(785, 163))
        self.main_frame.setMaximumSize(QtCore.QSize(785, 163))
        self.main_frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout.setContentsMargins(20, -1, -1, -1)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.h_lay = QtWidgets.QHBoxLayout()
        self.h_lay.setSpacing(0)
        self.h_lay.setObjectName("h_lay")
        self.checkBox = QtWidgets.QCheckBox(self.main_frame)
        self.checkBox.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.h_lay.addWidget(self.checkBox)
        self.del_btn = QtWidgets.QPushButton(self.main_frame)
        self.del_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.del_btn.setObjectName("del_btn")
        self.h_lay.addWidget(self.del_btn)
        self.verticalLayout.addLayout(self.h_lay)
        self.line = QtWidgets.QFrame(self.main_frame)
        self.line.setStyleSheet("background-color: #E4EAEE;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.people_lab = QtWidgets.QLabel(self.main_frame)
        self.people_lab.setObjectName("people_lab")
        self.verticalLayout.addWidget(self.people_lab)
        self.verticalLayout_2.addWidget(self.main_frame)

        self.retranslateUi(TodoForm)
        QtCore.QMetaObject.connectSlotsByName(TodoForm)

    def retranslateUi(self, TodoForm):
        _translate = QtCore.QCoreApplication.translate
        TodoForm.setWindowTitle(_translate("TodoForm", "Form"))
        self.checkBox.setText(_translate("TodoForm", "할일이름할일이름"))
        self.del_btn.setText(_translate("TodoForm", "삭제"))
        self.people_lab.setText(_translate("TodoForm", "함께하는 사람들"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TodoForm = QtWidgets.QWidget()
    ui = Ui_TodoForm()
    ui.setupUi(TodoForm)
    TodoForm.show()
    sys.exit(app.exec_())
